# This workflow will install Python dependencies, run tests and lint with a variety of Python versions

name: CI-Ubuntu

on:
  push:
    branches: [ '*' ]
    paths-ignore:         # Don't trigger on files that are updated by the CI
      - README.md
  pull_request:
    branches: [ '*' ]
  schedule:
    # * is a special character in YAML so you have to quote this string
    # run at 02:01 on the 3rd of each month
    - cron:  '1 2 3 * *'    

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10', '3.11']        
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip pytest pytest-cov pytest-flakes
    - name: Install the package
      run: |
        export SETUPTOOLS_ENABLE_FEATURES="legacy-editable"
        pip install -e .
        # Show f2py compiler info for debug
        f2py -c --help-fcompiler        
    - name: Run tests
      run: |
        pytest --pyargs SILEXlight.tests
